spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/alipay?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  # 启动配置文件
  profiles:
    active: dev
  # 配置时间格式和时差问题
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
  # 解决json返回过程中long的精度丢失问题
  generator:
    write-numbers-as-strings: true
    write-bigdecimal-as-plain: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # 解决bean重复定义的
  main:
    allow-bean-definition-overriding: true
  # dispatcherServlet 是懒加载机制,配置为1 表示提前加载
  mvc:
    servlet:
      load-on-startup: 1

# 日志配置管理
logging:
  level:
    root: info

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lonely.alipay_demo.entity

